openapi: 3.0.1
info:
  title: API de categorias
  description: API para controlar categorias
  version: 0.0.1
servers:
  - url: http://api/
    description: API de Categorias
paths:
  /categories:
    get:
      tags:
        - Categorias
      summary: Recupera todas as categorias
      responses: 
        200:
          description: Sucesso
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/Categories'
        404:
          description: Nenhuma categoria encontrada
          content:
            application/json:
              example:
                "Not Found"
  /categories/{id}:
    parameters: 
        - name: id
          in: path
          schema:
            type: integer
          required: true
    get:
      tags:
        - Categorias
      summary: Recupera uma categoria pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Category'
        404:
          description: Categoria n達o encontrada
          content:
            application/json:
              example:
                "Not Found"
  /admin/categories:
    post: 
      tags:
        - Categorias com acesso de admin
      summary: Cria nova Categoria
      requestBody:
        content: 
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: Sucesso ao criar categoria
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /admin/categories/{id}:
    parameters: 
        - name: id
          in: path
          schema:
            type: integer
          required: true               
    put:
      tags:
        - Categorias com acesso de admin
      summary: Atualiza uma Categoria
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryWithoutId'
      responses:
        200:
          description: Sucesso ao atualizar categoria
          content: 
            application/json:
              example:
                "Categoria atualizada com sucesso"
        404:
          description: Categoria n達o encontrada
          content:
            application/json:
              example:
                "Not Found"
    delete:
      tags:
        - Categorias com acesso de admin
      summary: Exclui uma categoria pelo ID
      responses:
        200:
          description: Sucesso ao deletar categoria
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Category'
        404:
          description: Categoria n達o encontrada
          content:
            application/json:
              example:
                "Not Found"
  /admin/categories/activate/{id}:
    put:
      tags:
        - Categorias com acesso de admin
      parameters: 
        - name: id
          in: path
          schema:
            type: integer
          required: true
      summary: Ativa uma Categoria
      description: Atualiza o status da categoria para 'ATIVA'
      responses:
        200:
          description: Sucesso ao atualizar status para 'ATIVA'
          content: 
            application/json:
              example:
                "Status da categoria atualizado para 'ATIVA' com sucesso"
        404:
          description: Categoria n達o encontrada
          content:
            application/json:
              example:
                "Not Found"
components:
  schemas: 
    Category:
      type: object
      properties: 
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    CategoryWithoutId:
      type: object
      properties:
        nome:
          type: string
        status:
          type: string
    Categories:
      type: array
      items:
        $ref: '#/components/schemas/Category'